name: CI

on:
  pull_request:
    branches: ['**']
    paths-ignore:
      - '*.md'

  push:
    branches: ['**']
    paths-ignore:
      - '*.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-code:
    name: Code Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup build
        uses: ./.github/actions/setup-build

      - name: Linting
        run: ./gradlew lint

  instrumentation-tests-player:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      total: ${{ steps.test-run.outputs.total }}
      skipped: ${{ steps.test-run.outputs.skipped }}
      failed: ${{ steps.test-run.outputs.failed }}
      failedTests: ${{ steps.test-run.outputs.failedTests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
    
      - name: Setup build
        uses: ./.github/actions/setup-build

      - name: Run Instrumentation tests for Player on Emulator
        # https://github.com/ReactiveCircus/android-emulator-runner
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew :ConvivaTestApp:assembleAndroidTest && ./gradlew ConvivaTestApp:connectedAndroidTest
