name: CI

on:
  pull_request:
    branches: ['**']
    paths-ignore:
      - '*.md'

  push:
    branches: ['**']
    paths-ignore:
      - '*.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation-tests-player:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      total: ${{ steps.test-run.outputs.total }}
      skipped: ${{ steps.test-run.outputs.skipped }}
      failed: ${{ steps.test-run.outputs.failed }}
      failedTests: ${{ steps.test-run.outputs.failedTests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
    
      - name: Setup build
        uses: ./.github/actions/setup-build

      - name: Run Instrumentation tests for Player
        run: ./gradlew connectedAndroidTest 
